version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "..//logs//app.log"
    mode: "a"

loggers:
  my_app:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [console, file_handler]
